import 'package:yazilim_muh_proje/Models/product.dart';

class ProductItems {
  static List<Product> items = [
    Product(
      id: 1,
      category: "Kadın Giyim",
      details: "Kırmızı elbise",
      name: "Ürün 1",
      price: 500,
      image: "images/elbise.jpg",
    ),
    Product(
      id: 2,
      category: "Erkek Giyim",
      details: "Gri sweatshirt",
      name: "Ürün 2",
      price: 300,
      image: "images/sweatshirt.jpg",
    ),
    Product(
      id: 3,
      category: "Kadın Giyim",
      details: "Kırmızı elbise",
      name: "Ürün 3",
      price: 200,
      image: "images/elbise.jpg",
    ),
    Product(
      id: 4,
      category: "Erkek Giyim",
      details: "Gri sweatshirt",
      name: "Ürün 4",
      price: 100,
      image: "images/sweatshirt.jpg",
    ),
    Product(
      id: 5,
      category: "Ayakkabı",
      details: "Kırmızı kız çocuk ayakkabı",
      name: "kız çocuk ayakkabı",
      price: 1000,
      image: "images/bebisayakkabı.jpg",
    ),
    Product(
      id: 6,
      category: "Ayakkabı",
      details: "Kırmızı kız çocuk ayakkabı",
      name: "kız çocuk ayakkabı",
      price: 1000,
      image: "images/bebisayakkabı.jpg",
    ),
    Product(
      id: 5,
      category: "Ayakkabı",
      details: "Kırmızı kız çocuk ayakkabı",
      name: "kız çocuk ayakkabı",
      price: 1000,
      image: "images/bebisayakkabı.jpg",
    ),
    Product(
      id: 7,
      category: "Ayakkabı",
      details: "Kırmızı kız çocuk ayakkabı",
      name: "kız çocuk ayakkabı",
      price: 1000,
      image: "images/bebisayakkabı.jpg",
    ),
    Product(
      id: 8,
      category: "Ayakkabı",
      details: "Kırmızı kız çocuk ayakkabı",
      name: "kız çocuk ayakkabı",
      price: 1000,
      image: "images/bebisayakkabı.jpg",
    ),
    Product(
      id: 5,
      category: "Ayakkabı",
      details: "Kırmızı kız çocuk ayakkabı",
      name: "kız çocuk ayakkabı",
      price: 1000,
      image: "images/bebisayakkabı.jpg",
    ),
    Product(
      id: 9,
      category: "Ayakkabı",
      details: "Kırmızı kız çocuk ayakkabı",
      name: "kız çocuk ayakkabı",
      price: 1000,
      image: "images/bebisayakkabı.jpg",
    ),
  ];
}
